### ISSUE TITLE
/ch help - 誤字

### ISSUE THREAD

**Issue by rain318** [ucchyocean/LunaChat#127]
[src/main/resources/messages.yml#L183](https://github.com/ucchyocean/LunaChat/blob/master/src/main/resources/messages.yml#L183) が**f=data**になってますよー。

before
```
usageLog: '&6/%s log [channel] [p=player] [f=filter] [f=date] [r] &7- チャンネルの発言ログを表示します。'
```

after
```
usageLog: '&6/%s log [channel] [p=player] [f=filter] [d=date] [r] &7- チャンネルの発言ログを表示します。'
```

**Comment by pabook** [comment]
ご報告有り難うございます、修正しました。
