### ISSUE TITLE
チャンネルチャット無効状態でも、/ch hide (player) コマンドを使って、指定したプレイヤーの発言やtellコマンドを無視できるようにして欲しい。

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/LunaChat#131]
フォーラムにて頂いた要望。

-----
自鯖ではEssentialsChatと併用してlunachatを使っているのですが、Essentialsのignore（特定プレイヤーの発言を無視）コマンドを使ってもlunachatのプライベートメッセージとして個人チャットが送ることが出来てしまい、困っています。
チャンネルチャット機能は使用していませんので、/ch hideコマンドも使用出来ません。
そこで提案というか要望なのですが、lunachatでも /ignore PLAYERNAME コマンドでプライベートメッセージを無視出来るようには出来ないでしょうか？
それが無理であれば、lunachatのプレイベートメッセージ機能をオフに出来る設定があれば助かります。

現状はチャンネルチャット機能をtrueにした状態でlunachat.join、lunachat.create等のパーミッションを奪っている状態です。
プレイヤーは/ignoreコマンドと/ch hideコマンドを使わなければならず、不便を強いている状態です。

-----

**Comment by ucchyocean** [comment]
LunaChat から、EssentialsChatでの無視状態を取得することは、あまり現実的ではないので、対応しない。
それよりも、チャンネルチャット無効状態でも、`/ch hide (player)`コマンドを使って、指定したプレイヤーの発言やtellコマンドを無視できるようにすればよい。
ちなみに、通常チャットは`/ch hide (player)`コマンドの非表示対象ではないので、この際に合わせて対応を加えたい。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK

**Comment by Laica-Lunasys** [comment]
恐らく、EssentialsChatのミュート機能は、単にチャットのイベントをキャンセルしている物と思われます。
Essentialsは勿論、他のプラグインからの発言抑止を行う為にも、必要では無いでしょうか？
クローズされたIssueにて失礼します。

**Comment by ucchyocean** [comment]
あれ、混在した環境で動作確認したら、EssentialsChatではキャンセルされていなかったことを確認しましたし、ソースコードも確認してRecipientを変更していることを確認しています。
何か、今回のLunaChatの変更で、うまく動いていないところや、変なところがありました？

**Comment by Laica-Lunasys** [comment]
EssentialsChatにはignoreコマンドは実装されていない筈です。(前述にて記載ミスしてしまいました)
Essentialsのignore機能は、AsyncPlayerChatEventのキャンセルで実現できているようです。
ucchy氏の仰る、「混在する環境下でEssentialsChatではキャンセルされないことを確認しました」は、EssentialsChatをメインに使用している場合(LunaChatはJapanizeだけ)の時でしょうか？

**Comment by ucchyocean** [comment]
確かに、チャンネルチャット無効状態で、EssentialsChatとLunaChatの混在検証をしただけですが・・・
うーん、キノセイだったのかな？　再確認をして、EssentialsChatとLunaChatの混在環境で問題があるのかどうか、確認してみます。

**Comment by ucchyocean** [comment]
EssentialsChatとLunaChatの混在環境で、両者とも影響が無く、混在して動作できることを確認しました。
まあ、特に問題はないでしょう。
LunaChatの今回の対応で、ignoreCancelled=true を入れていて、EssentialsChatでキャンセルされていたらLunaChatの動作をしないように対応していたのですが・・・
動作確認をしたところ、問題は無いようですね。よかったです。

**Comment by Laica-Lunasys** [comment]
了解しました。
ありがとうございます。
