### ISSUE TITLE
"<-"と単体でチャットを送信すると"\u003cー"と変換される

### ISSUE THREAD

**Issue by syokkendesuyo** [ucchyocean/LunaChat#135]
環境
Spigot 5f38d38　(MC:1.8.8 R0.1 SNAPSHOT)
LunaChat 2.7.1
CentOS release 5.5 (Final)

**Comment by ucchyocean** [comment]
デバッグ実行結果
<pre>
kana : <ー
GoogleIME : \u003cー
SocialIME : &lt;ー
</pre>
サニタイズが足りていないのかな。
`&gt;``&lt;``&amp;``&quot;` この辺りは、GoogleIMEに送る前に全角変換しておく。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
![2015-12-08_22 16 28](https://cloud.githubusercontent.com/assets/2563444/11656577/7dc473e4-9df9-11e5-8fdf-9783cae18b58.png)
