### ISSUE TITLE
SocialIMEサービス終了に関して

### ISSUE THREAD

**Issue by Laica-Lunasys** [ucchyocean/LunaChat#146]
Social IMEが2016年9月1日で終了しますので、configからの除去(実装も？)するべきかと思います。
http://www.social-ime.com/

宜しくお願いします。

**Comment by ucchyocean** [comment]
情報ありがとうございます。次バージョンアップで対応しましょう。
しばらく家には不在なので、対応は8月8日以降に開始しますが、ご了承ください。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
