### ISSUE TITLE
hideしたいプレイヤーの名前と同名のチャンネルが存在するときプレイヤーをhideできない

### ISSUE THREAD

**Issue by hisuie08** [ucchyocean/LunaChat#153]
例えばabcdというプレイヤーをhideしたいとき、サーバー内にabcdというチャンネルが存在すると/ch hide abcdと入力したときチャンネルのみがhideされプレイヤーをhideすることができない不具合があります。プレイヤーUUIDを入力しても機能しませんでした。
プレイヤー名とチャンネルと区別した入力ができるようお願いしたいです。

**Comment by rona-tombo** [comment]
以下のプルリクエストで修正を行っています
https://github.com/ucchyocean/LunaChat/pull/154

**Comment by ucchyocean** [comment]
Fixed
動作確認OK

従来の
`/ch hide (Player名 または Channel名)`
に加えて、
`/ch hide player (Player名)`
`/ch hide channel (Channel名)`
が指定できるようになりました。
