### ISSUE TITLE
イベント発火が、イベント発火後の処理と同期されていない

### ISSUE THREAD

**Issue by LazyGon** [ucchyocean/LunaChat#162]
現状、`Utility#callSyncEvent`でイベントを同期でスケジュールして実行していますが、これはメインスレッドの中で1tick後にイベント発火を実行するという処理になります

なので、
* 非同期で行われるチャットの処理とイベントの発火が同期されていない
* そもそも1tick後にイベントを発火するから、イベント発火以降の処理が外部からのイベント操作より先に実行されてしまう

これらの問題が起き、イベント処理が無意味になっています

キャンセルしようとしてもキャンセルできませんでしたし...

上の問題のうち、1tick後に実行されてしまうことを再現するテストを書きました
https://github.com/LazyGon/TestPL/blob/master/src/main/java/com/github/lazygon/testpl/TestListener.java#L30

この処理の結果は以下のようになります

![実験結果](https://user-images.githubusercontent.com/26216029/68519942-963c9b80-02d7-11ea-9f24-2c8e6ab6f81e.png)

**Comment by LazyGon** [comment]
この解決策としては、ちゃんと非同期用のイベントクラスを作って非同期な場所にはそのイベントを使用するか、イベントをnewするときの引数にboolean asyncを追加するかのどちらかが必要です
スケジュールで呼び出して楽しようとしてはいけません

**Comment by LazyGon** [comment]
問題を再現したい場合は、外部にLunaChatに依存するプラグインを作り、何かしらの値をsetしてみれば良いです
それが適応されないことがすぐに分かります
わかりやすい `Cancellable#setCancelled` で試すのが良いでしょう

**Comment by LazyGon** [comment]
プルリクエスト#163で修正しました
問題なければマージをお願いします

**Comment by ucchyocean** [comment]
マージさせていただきました。ありがとうございました。
