### ISSUE TITLE
`/ch list`のページング

### ISSUE THREAD

**Issue by mirror-kt** [ucchyocean/LunaChat#164]
チャンネル数が多いとチャット欄全域に表示しきれず見切れてしまいます。
一定の数を超えている場合は`/ch list 1`、`/ch list 2`などのようにページを分割することを提案します。
PRを書いたほうがいい場合は書きます。

**Comment by ucchyocean** [comment]
@mirror-kt さん
遅くなってすみません。
ページングに対応してみました。
https://github.com/ucchyocean/LunaChat/releases/tag/v2.8.13
から、LunaChat.jar を取得して試してみてください。

* `/ch list` を実行した場合は、従来通り、すべてのチャンネルを表示します（ただし、チャンネル名を辞書順にソートするようにしました）。
* `/ch list 1` や `/ch list 2` のように、後ろにページ番号を付けると、指定のページを表示するようになります。
* `/ch list 999` など、存在しないページを指定した場合は、最後のページを表示します。

![2020-04-27_13 59 11](https://user-images.githubusercontent.com/2563444/80336201-933b6480-8891-11ea-9349-aea326b17c3e.png)
