### ISSUE TITLE
フォーマットのキーワード追加

### ISSUE THREAD

**Issue by shadowpot** [ucchyocean/LunaChat#165]
config.ymlから設定できるフォーマットについて、機能追加の要望です。
チャンネル内のチャットやプレイベートメッセージでは%playerというキーワードが使えるようですが、チャンネルに所属してないチャットだと使用できませんでしたので追加をお願いします。

**Comment by ucchyocean** [comment]
すみません、ご要望の内容がよくわからなかったので、詳しく記載してほしいのですけれども、
やってほしい事は、「フォーマットのキーワード追加」ではなく、
「"チャンネルに所属していないプレイヤーの発言は%usernameや%playerのキーワードが適用されない"、という不具合の修正」ということでしょうか？

**Comment by shadowpot** [comment]
返信が遅れてしまって申し訳ないです。
こちらで使わせて頂いているLunaChat ver2.8.13だと、config.ymlの165行目以降、「normalChatMessageFormat」の項目の上にあるコメントに%playerがありませんでした。
また、%usernameはコメントにもあり使用できました。
チャンネル外チャットでは実装されていないだけで不具合ではない、と認識したので機能追加の要望として送らせて頂きました。

やって頂きたいことは、「チャンネルに所属していないプレイヤーの発言に%playerのキーワードが適用されるようにしてほしい」です。
わかりづらい要望を送ってしまい、申し訳ありません。

**Comment by ucchyocean** [comment]
了解です。意図を理解できました。
「normalChatMessageFormat設定で、%playerキーワードを使えるようにしてほしい」というご要望ですね。
すぐ対応できると思います。

**Comment by ucchyocean** [comment]
対応してみましたので試してみてください。

https://github.com/ucchyocean/LunaChat/releases/tag/v2.8.15
から、LunaChat.jar を取得して上書きしてください。

`LunaChat\config.yml` の `normalChatMessageFormat` 設定に、`%player` キーワードを加えると、発言者のプレイヤー名が表示されるようになるはずです。

**Comment by shadowpot** [comment]
確認できました。
対応ありがとうございました！
