### ISSUE TITLE
BungeeCord対応について

### ISSUE THREAD

**Issue by tererun** [ucchyocean/LunaChat#166]
いつもLunaChatを使わせていただいているのですが、BungeeCord間のサーバーで連携させたいと思ったのですが、うっちぃさんの「BungeeJapanizeMessenger」を使用すると、プライベートチャンネルの内容も出てきてしまうので、できればLunaChatにもBungeeCord対応の機能を付けてほしく存じます。
提案ではございますが、よろしくお願いします。

**Comment by ucchyocean** [comment]
BungeeJapanizeMessenger の `broadcastChatLocalJapanize: ` 設定は、false になっていますか？
`broadcastChatLocalJapanize: false` にしているけれども、プライベートチャンネルの発言内容が BungeeJapanizeMessenger で表示されてしまっている状態ですか？

**Comment by tererun** [comment]
`broadcastChat`を`true`にしたところ、通常のチャット(所謂グローバルチャット)が共有されなくなってしまったのですが、プライベートチャットは大丈夫なようです。

**Comment by ucchyocean** [comment]
`broadcastChat: false` にしたら、チャット発言はサーバー間で共有されなくなりますが、`/tell`コマンドなどではサーバーをまたいで連絡することが可能です。
`broadcastChat: true` にした場合は、チャット発言がすべてのサーバーで表示されますが、各サーバーのローカルでチャンネルチャットを運用することは不可能です。
config.ymlにも記載している通り、現状の仕様ですのでご了承ください。
BungeeCordプラグインで、チャンネルチャット機能を提供しているプラグインが他にもありますので、探してみてくださいね。
