### ISSUE TITLE
maven shade pluginでjarのコンパクト化を検討

### ISSUE THREAD

**Issue by LazyGon** [ucchyocean/LunaChat#179]
[このページ](https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html)で説明されている`minimizeJar`を`true`にすることで、shadeされる依存の内、使われていないコードを自動的に排除して容量を削減できます。
v3の容量が1MBもあるのはcommons-lang3やgsonをshadeした分が大きいと思うので、ぜひ検討してみてください。

※ほぼ大丈夫とは思いますが、使った結果バグらないとは言い切れないので実働環境で問題が起きないかなどは調べてみるべきではあります。

**Comment by ucchyocean** [comment]
ご提案ありがとうございます。
一行足すだけですし、次のタイミングで対応を加えておきます。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK

ファイルサイズは、1.105KB -> 749KB に、
shadeで導入されるクラス数は 688 -> 427 に
なりました。
