### ISSUE TITLE
jp on(off)コマンドが使えません。

### ISSUE THREAD

**Issue by lee3kfc** [ucchyocean/LunaChat#180]
v3.0.1 beta 以降、**/jp on(off)**コマンドが使えません。
paperc;lip-74で鯖を建てて、プラグインフォルダにはlunachat.jarのみ、3.0.1 beta ～ 3.0.3 beta の三種類ためしてみましたが/jp offとコマンドを打つと
/jp on|off - turn on/off the japanize conversion of your chat.
/jp (player) (on~off) - turn on/off the japanize conversion of the specified player's chat.
と表示され、実際には切り替わりませんでした。
同じ環境でv2.8.10を使って起動してみたところ、問題なく使えました。

**Comment by ucchyocean** [comment]
現象を確認しました。
LunaChatのコマンドが実行されたときに、`/jp` コマンドの識別子の判別箇所で実装ミスがあり、正しくコマンドが実行されていませんでした。失礼しました。
すぐ修正しますので、修正済みの v3.0.4 をご利用ください。

**Comment by lee3kfc** [comment]
ありがとうございます！

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
![2020-07-06_23 25 34](https://user-images.githubusercontent.com/2563444/86609705-4689ad80-bfe7-11ea-90f0-7bf2030fe6a0.png)

**Comment by ucchyocean** [comment]
本件を修正した v3.0.4 を用意しましたので、こちらをご利用ください。
https://github.com/ucchyocean/LunaChat/releases/tag/v3.0.4
