### ISSUE TITLE
v3.0.3betaにおいて、MintChatBotが機能しません。

### ISSUE THREAD

**Issue by lee3kfc** [ucchyocean/LunaChat#181]
表題の通りです。
v3.0.2betaに戻すと機能しました。

**Comment by ucchyocean** [comment]
LunaChatのv3.0.3から、 #178 の対応により、通常のチャットをキャンセルしてjsonメッセージを流すようになり、
MintChatBotは、AsyncPlayerChatを `priority=EventPriority.HIGHEST, ignoreCancelled=true` （できるだけ最後の方に動作し、他のプラグインがチャットメッセージイベントをキャンセルした場合は動作しないような設定）でリッスンしているため、
LunaChat v3.0.3 の通常チャット運用と、MintChatBotの組み合わせで動作しなくなった、ということが起きているようです。

どちらを直すべきなのか、ちょっと悩みますね。。。
少し検討させてください。

ちなみに回避策として、LunaChatのconfig.ymlで、グローバルチャンネルを設定して運用するようにしたら、MintChatBotとの組み合わせでも期待通りに動作するはずです。

**Comment by ucchyocean** [comment]
MintChatBotのイベントリッスンのプライオリティをNORMALに変更してみました。
https://github.com/ucchyocean/MintChatBot/releases/tag/v2.5.3

これと、LunaChat v3.0.4 を組み合わせてみて試してみてください。

**Comment by ucchyocean** [comment]
ひとまず本イシューは閉じておきます。
今後、他プラグインとの連携でうまくいかない場合は、都度対応いたします。
