### ISSUE TITLE
BungeeCordにおけるワールド名表示

### ISSUE THREAD

**Issue by lee3kfc** [ucchyocean/LunaChat#182]
Bungeecordにlunachat v3.0.4beta を導入してみたのですが、すべてのサーバーにおいてチャットにワールド名が表示されなくなりました。

**Comment by ucchyocean** [comment]
現状の仕様通りの動作です。
BungeeCordプラグインからは、プレイヤーの位置を取得できないため、ワールド名が表示できません。
同じ理由で、ワールドチャットや範囲チャットも使用できません。
ご了承ください。

次のバージョンアップで対応を検討しています。

**Comment by ucchyocean** [comment]
LunaChat v3.0.7 で対応しました。

BungeeCord・Spigotの全サーバーにLunaChatを導入し、すべての config.yml で bungeePassThroughMode を true に設定してください。
BungeeCordではチャットイベントをスルーし、Spigotまで到達したら、BungeeCordに送り返してチャンネルチャット発言をします。
そのため、Spigot層でチャットに連携している他プラグインも動作するようになります。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
![Screenshot_20200725-230433](https://user-images.githubusercontent.com/2563444/88459701-4ee05480-ced2-11ea-983b-49a6b03db462.png)
