### ISSUE TITLE
BungeecordにおけるMintChatBot

### ISSUE THREAD

**Issue by lee3kfc** [ucchyocean/LunaChat#183]
Bungeecordにlunachat v3.0.4を導入しましたが、MintChatBotが機能しなくなりました。

**Comment by ucchyocean** [comment]
すみませんが、こちらについても現状の仕様通りの動作です。
BungeeCord導入の場合は、BungeeCordの層でチャットイベントの処理が終了するため、Bukkit(Spigot/Paper)のところまでチャットイベントが到達しません。
ご了承ください。

#182 と同様、次のバージョンでの対応を検討しています。

**Comment by ucchyocean** [comment]
LunaChat v3.0.7 で対応しました。

BungeeCord・Spigotの全サーバーにLunaChatを導入し、すべての config.yml で bungeePassThroughMode を true に設定してください。
BungeeCordではチャットイベントをスルーし、Spigotまで到達したら、BungeeCordに送り返してチャンネルチャット発言をします。
そのため、Spigot層でチャットに連携している他プラグインも動作するようになります。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
![Screenshot_20200725-230433](https://user-images.githubusercontent.com/2563444/88459749-96ff7700-ced2-11ea-8cb9-80741d11742d.png)
