### ISSUE TITLE
グローバルチャットがコンソールに表示されない。

### ISSUE THREAD

**Issue by lee3kfc** [ucchyocean/LunaChat#190]
```
# チャンネルチャットの発言内容を、サーバーコンソールに表示するかどうか
displayChatOnConsole: true
```

とconfigで設定可能ですが、

```
# 通常のチャットの代わりに、既定として使用するグローバルチャンネル。
# グローバルチャンネルを作らず通常のチャットを使用する場合は、
# から文字列 「''」 を指定すること。
globalChannel: ''
```

と、グローバルチャンネルを作成しなかった場合にサーバーコンソールにチャットログを表示させる手段がありません。

**Comment by ucchyocean** [comment]
ご報告いただきありがとうございます。
Bukkit側導入ですか？　BungeeCord側導入ですか？

**Comment by ucchyocean** [comment]
Bukkit側導入、BungeeCord側導入（bungeePassThroughModeがtrueの場合もfalseの場合も）を試してみましたが、
いずれも通常チャットはサーバーコンソールに表示されることを確認しました。
こちらで使っているサーバーは、Spigot および BungeeCord です。
他のサーバーだと表示されていないでしょうか？ PaperとかWaterfallとか？

**Comment by lee3kfc** [comment]
Waterfall経由（Bungee用チャットプラグイン無し）のPaperです。
お手数かけてすみません。再度確認してみます。

**Comment by lee3kfc** [comment]
すみません、解決しました。
Waterfall ＃366 下のpaperclip-115で運用している２つの鯖において、それぞれlunacat3.0.4betaと3.0.5betaを使用していましたが、双方とも3.0.7betaにアップデートしたことでコンソールに表示されるようになりました。
