### ISSUE TITLE
個人チャットが送信されずグローバルで発言してしまう。

### ISSUE THREAD

**Issue by lee3kfc** [ucchyocean/LunaChat#191]
**Describe the bug/バグの概要**

**Server and version/サーバーとバージョン**
- Server: Waterfall 366, Paper 115
- Server version (Minecraft version) : 1.16.1
- Other plugins: 
    Waterfall:  floodgate-bungee24, Geyser-Bungeecord286, HubCommand1.1, LunaChat3.0.7, nuvotifier-2.7.1, PL-Hide-Pro-1.1.1, protocolize-pluguin, slingshot-2.0
    Paper: Essentials, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, LuckPerms, LunaChat*, Multiverse-Core, Multiverse-Portals, SimpleVoteListener*, Vault, Votifier, WorldBorder, WorldEdit, WorldGuard

- LunaChat version : 3.0.7beta

**To Reproduce/再現手順**
1. PlayerA が PlayerBに大してlunachatの個人チャット（ /msg 等）コマンドを使用
2. ワールド名が表示されず、内容が全体チャットに表示される。

**Expected behavior/期待する結果**
プライベートメッセージは全体チャットに表示されないことを期待。

**Screenshots/スクリーンショット**
If applicable, add screenshots to help explain your problem./スクリーンショットがあれば添付してください。ブラウザに画像ファイルをドラッグアンドドロップしてアップロードできます。
![2020-07-27_02 40](https://user-images.githubusercontent.com/1352107/88485933-1ebdb200-cfb5-11ea-8dcb-4ec3425a608b.png)
![2020-07-27_02 40 19](https://user-images.githubusercontent.com/1352107/88486061-f4b8bf80-cfb5-11ea-8415-bd96bb474067.png)

**Additional context/備考**
EssentialsXのウィスパーコマンド /w は問題なく使える状態です。

**Comment by ucchyocean** [comment]
ご報告いただきありがとうございます。
今日帰宅したら、再現確認をしてみます

**Comment by ucchyocean** [comment]
BungeeCord + Spigot + LunaChat v3.0.7 (bungeePassThroughMode構成) で確認していますが、今のところ再現を確認できていません。
![2020-07-28_00 07 23](https://user-images.githubusercontent.com/2563444/88558533-9e578980-d066-11ea-8097-2c979f6b1bec.png)

Waterfall + Paper + LunaChat v3.0.7 (bungeePassThroughMode構成) の環境も作って検証してみます。

**Comment by ucchyocean** [comment]
うーん、Waterfall + Paper + LunaChat を試してみたのですけれども、やはり再現を確認できません。
![2020-07-28_00 28 29](https://user-images.githubusercontent.com/2563444/88560783-85040c80-d069-11ea-8b1a-a80f847f972f.png)

試した環境は、waterfall-366、paper-117、LunaChat v3.0.7 (bungeePassThroughMode構成) の組み合わせです。

もし、`/tell` `/msg` などのコマンドがまだ期待通りに動かないようでしたら、Waterfall側のログファイルを確認し、どこかでエラーが発生していないかご確認をいただけますか。
エラーがあるようなら、その内容を返信でご連絡いただけると助かります。

**Comment by lee3kfc** [comment]
失礼しました。
defaultFormatForPrivateMessage:　と　normalChatMessageFormat:　を同じ設定にしてあったため、全体チャットに表示されていると勘違いしていました。
ご迷惑をおかけして申し訳ありません。
