### ISSUE TITLE
whisper（/w)コマンドを追加してほしい

### ISSUE THREAD

**Issue by lee3kfc** [ucchyocean/LunaChat#193]
**Is your feature request related to a problem? Please describe.**
EssentialsXを導入してlunachatと併用しているが、個人チャットを送信する/wまたは/whisperコマンドを使用した場合、それに返信する場合の/rコマンドはlunachatが優先されるのでチャットフォーマットが違うものになってしまう。

**Describe the solution you'd like**
lunachat側で/wまたは/whisperコマンドにも対応してほしい。

**Describe alternatives you've considered**
⚫サーバーのcommands.ymlに aliases: w: - msg $$1 $$2- と記述し置き換えてみたが、

1. 個チャ送信対象であるプレイヤーが別のサーバーに居る場合に /w *** testとコマンドした場合は
[LC]The specified player *** cannot be found.
とエラー表示される。/msgコマンドでは問題なく別サーバーへ送信可能。

2. 個チャ送信対象であるプレイヤーが同じサーバーに居る場合に /w *** testとコマンドした場合は
全体チャットで***と発言してしまう。

**Additional context**
多くのプレイヤーが /w コマンドを利用するため、是非lunachatでも対応してください。よろしくおねがいします。

**Comment by ucchyocean** [comment]
Fixed
LunaChat v3.0.8 以降で対応済みです。

BungeeCord側に導入したときのAliaseに、`/w` を追加しました。
Spigot側導入時は、Spigotのcommands.yml で対応してください。

なお、今回の場合はどちらかというと、Spigot側のパーミッションで `essentials.msg` を落として、一般プレイヤーにEssentialsXの `/w` コマンドへアクセスさせないようにする方がより適切な解決ではないかと思います。ご検討ください。
（EssentialsXのエイリアスは`/w`のほかに、`/etell` `/whisper` `/ewhisper` があるみたいですし、`/w`をつぶしただけだと、他のエイリアスでアクセスされてしまうと思います。）
