### ISSUE TITLE
Bungeecord下における/ch hideコマンド

### ISSUE THREAD

**Issue by lee3kfc** [ucchyocean/LunaChat#194]
**Describe the bug/バグの概要**
特定のプレイヤーの発言をignoreしようとし、/ch hide PLAYERNAME とコマンド入力すると
> [LC]権限 "lunachat.hide"が無いため、実行できません。

とエラーが返ってきたので、BungeeCord側にLuckPermsBungeeを導入し、権限を与え再度コマンド入力すると
> [LC]指定されたチャンネルもプレイヤーも存在しません。

とエラーが返ってくる。

**Server and version/サーバーとバージョン**
- Waterfall 366 / paper 117
- Server version 1.16.1
- Other plugins: 
    Waterfall: LuckPermsBungee-5.1.84
    Paper: Essentials-X2.18.0.0
- LunaChat version : 3.0.7

**To Reproduce/再現手順**
1. waterfall366をDLしbatファイルを作成、起動、上記２つのプラグインを導入し再起動。
2. WaterfallのLunaChatのconfig.yml最終行bungeePassThroughMode: をtrueに変更しch reload。
3. paper117をDL、batファイルを作成し起動。上記２つのプラグインを導入、server.propatiesのonline-mode=false, spigot.ymlのbungeecord: trueに設定し再起動。lunachatのconfig最終行bungeePassThroughMode: をtrueに変更しch reload。
4. PlayerA、PlayerBでログインし、PlayerAで/ch hide PlayerBとコマンド入力➔ lunacat.hideが無いエラー
5. Waterfallコンソールで lpb group default permission set lunachat.hide true と権限付与し再度コマンド➔ chもプレイヤーも無いとエラー

**Expected behavior/期待する結果**
/ch hide PLAYERNAMEを使用するとどのサーバーに居ても該当プレイヤーの発言を無視することが出来ることを期待。

**Screenshots/スクリーンショット**
If applicable, add screenshots to help explain your problem./スクリーンショットがあれば添付してください。ブラウザに画像ファイルをドラッグアンドドロップしてアップロードできます。

**Additional context/備考**
サーバー間での無視機能が有効か確認しようとし、コマンドが効かないので同じサーバーに居る状態で試してみてもやはりコマンドが使えず困っています。
EssentialsXの/ignoreコマンドは利用可能ですが、lunaチャットの発言は無視されず、/ignore 状態でも /unignore 状態でも発言は見えてしまう状態です。
出来れば一般的に馴染みのある/ignoreコマンドで無視出来た方が便利だと思います。

**Comment by ucchyocean** [comment]
再現することを確認しました。
修正の検討を開始します。

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
LunaChat v3.0.8 で修正版をリリースします。
