### ISSUE TITLE
ウェブカラーコードがコンソールに反映されない

### ISSUE THREAD

**Issue by graycat27** [ucchyocean/LunaChat#196]
**Describe the bug/バグの概要**
#176 によって追加された機能により、カラー指定を行い、チャット発言をした際、コンソールに当該カラー指定が反映されない

**Server and version/サーバーとバージョン**
- Server: Spigot 
- Server version (Minecraft version) : 1.16.1
- Other plugins: FastAsyncWorldEdit-1.16 / Jecon / Vault
- LunaChat version : 3.0.7

**To Reproduce/再現手順**
(前提状態)チャンネルはグローバル。 /jp off にて変換off状態
（a. 単純な再現ケース）
1. チャット発言「#272727test」
2. Minecraft内表示「test」(暗い灰色)
3. コンソール内表示「test」(白色)

（b. 比較ケース）
1. チャット発言「&atest」
2. Minecraft内表示「test」(緑色)
3.コンソール内表示「test」(緑色)

**Expected behavior/期待する結果**
a.3とb.3でコンソールでの表示色に差異がある。
a.3においても、Minecraft内と同様の色で出力されることを予期していた。

**Screenshots/スクリーンショット**
手順a の結果（2. 3. ）表示色が乖離している
![image](https://user-images.githubusercontent.com/64903817/88803849-0aadc680-d1e8-11ea-89db-1632dbc1418a.png)

手順b の結果（2. 3. ）表示色が合致している
![image](https://user-images.githubusercontent.com/64903817/88803958-32049380-d1e8-11ea-800b-55cfdf0a851a.png)

**Additional context/備考**
発言に両方の指定方法を混在させた場合、#webColorCode は無視された状態でコンソールに出力される
![image](https://user-images.githubusercontent.com/64903817/88804595-206fbb80-d1e9-11ea-8709-ee2376b9a339.png)

**Comment by ucchyocean** [comment]
LunaChatからコンソール表示用に送っている文字列は、ウェブカラーコードを含んだ状態になっています。
Spigotがコンソールに表示する際に、ウェブカラーコードだけ除去しているみたいですね。

Linuxのコンソールは24ビットカラーコードに対応しているものもあるみたいですが、
Windowsのコマンドプロンプトなどは16色にしか対応していませんので、
コンソールで問題が起きないように、Spigotがコンソールにメッセージを表示する際にウェブカラーコードを除去しているのだと思われます。

Spigotの動作仕様ということでご了承ください。イシューは閉じさせてもらいます。
