### ISSUE TITLE
[BungeeCord] LuckPerms より先に LunaChat が読み込まれると起動に失敗する

### ISSUE THREAD

**Issue by Siroshun09** [ucchyocean/LunaChat#199]
**Describe the bug/バグの概要**
LunaChat と LuckPerms を入れた状態で起動すると、LuckPerms API の取得に失敗することがあります。

具体的には、 LunaChat → LuckPerms の順で有効化 (`onEnable()`) されると、LuckPerms のプラグインインスタンスは取得できるが、`LuckPermsProvider` に LuckPerms API がセットされてないため、取得時に `IllegalStateException` が投げられます。 ( https://javadoc.io/static/net.luckperms/api/5.1/net/luckperms/api/LuckPermsProvider.html#get-- )

```
[08:24:37] [main/WARN]: Exception encountered when loading plugin: LunaChat
java.lang.IllegalStateException: The LuckPerms API is not loaded.
	at net.luckperms.api.LuckPermsProvider.get(LuckPermsProvider.java:50) ~[?:?]
	at com.github.ucchyocean.lc3.bridge.LuckPermsBridge.load(LuckPermsBridge.java:39) ~[?:?]
	at com.github.ucchyocean.lc3.LunaChatBungee.onEnable(LunaChatBungee.java:95) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
```

**Server and version/サーバーとバージョン**
- Server: Waterfall
- Server version (Minecraft version) : 1.16.1 / 1.15.2
- Other plugins:  LuckPerms 5.1.86 DiscordChatBridge など (起動時の問題なので、他 PL は略させていただきます)
- LunaChat version : 3.0.8

**To Reproduce/再現手順**
1. LunaChat と LuckPerms を入れた状態で起動する
2. LunaChat が LuckPerms より先に有効化されると、`LuckPermsProvider` から API の取得に失敗する

**Comment by ucchyocean** [comment]
ご報告いただきありがとうございます。
今日帰宅したら調査してみます

**Comment by Siroshun09** [comment]
すみません、こちらで使ってる [DiscordChatBridge (Discord とのチャット連携)](https://github.com/okocraft/DiscordChatBridge) も起動順に影響を与えていたかもしれません。

DiscordChatBridge は LunaChat に依存しているため、LunaChat より後に読み込まれます。

DiscordChatBridge (というよりかは LunaChat に依存しているプラグイン) → LuckPerms の順で読み込まれると、必然的に LunaChat → LuckPerms で読み込まれます。

また、LunaChat に依存しているプラグインがなくても、読み込み順は `java.io.File#listFiles` で返される配列によるので、この問題が起きる可能性はあります。

とりあえずの解決策として、 LunaChat の `bungee.yml` に `softdepend: [LuckPerms, BungeePerms]` を追記することで正常に起動できました。

**Comment by ucchyocean** [comment]
調査していただきありがとうございます。
bungee.yml にも、softDepends を書くことができたのですね。不勉強ですみません。
修正内容として、`softDepends: [LuckPerms, BungeePerms]`の追記で良いと思います。次のバージョンで対応しておきます。

**Comment by Siroshun09** [comment]
`plugin.yml` の soft depend がちょっと複雑というか、正式な指定方法が曖昧だったので、一応報告しておきます

[plugin.yml の Wiki](https://www.spigotmc.org/wiki/plugin-yml/) にある通りに `softdepend: []` で設定するとロード順の変化が見られませんでした。

謎だったので BungeeCord のソースコード [`PluginDescription.java`](https://github.com/SpigotMC/BungeeCord/blob/15b514130eb861cb44ddc787aa152f73e259dbb1/api/src/main/java/net/md_5/bungee/api/plugin/PluginDescription.java#L42) を見てみると、lombok を使ってるため変数名しかわかりませんが、`softDepends` になっています (SnakeYaml の `Yaml#loadAs` の仕様からすれば、これが設定パス)。

一方、IntelliJ で使用できる JSON Schema の [SchemaStore.org BungeeCord plugin.yml](https://json.schemastore.org/bungee-plugin) では `softdepends` となっています。

おそらく `softDepends` か `softdepends`、もしくは両方とも許容されるかのどれかかと思いますが、そこまで調査できていません、申し訳ないです。

**Comment by ucchyocean** [comment]
調査していただきありがとうございます。
LunaChatの外から、LunaChatにgetDescription()して、softDependsが設定されているか確認してみましたが、
`softdepends` だとダメですね。`softDepends` ならOKのようです。
`softDepends: [LuckPerms, BungeePerms]` の追記で正しそうです。

**Comment by ucchyocean** [comment]
Fixed.
