### ISSUE TITLE
チャットログをBungeeCordではなくspigot側のコンソールログに残したい。

### ISSUE THREAD

**Issue by lee3kfc** [ucchyocean/LunaChat#200]
**Is your feature request related to a problem? Please describe.**
BungeeCordにlunachatを入れてチャットを統括した場合に、全てのサーバーのログがBungeeCordに流れてしまい、各サーバーのログには残りません。個人的にはBungeeCordをチャットのログで汚すのは好ましくないと考えていますし、各サーバーのチャットの流れと他のログとを見るために、各サーバーごとにチャットのログが残るのが好ましいと思っています。

**Describe the solution you'd like**
バンジー側かサーバー側か、configにチャットのログを残す選択肢がほしい。

**Describe alternatives you've considered**
configで上記の設定が難しいのであれば、サーバー側でのみログを残すようにしてほしい。

**Additional context**
Waterfall366 + lunachat3.0,9 + LuckPerms 5.1.86
paperclip-131 + lunachat3.0.9 + Essentials 2.18.0
で、双方ともlunachatのconfigをデフォルトから下記３点を変更した状態で検証しました。
enableChannelChat: false
loggingChat: false
bungeePassThroughMode: true

また、この状態でbungee側のconfigで
displayChatOnConsole: false
とした場合に下記の警告が表示されます。
[13:36:51] [Netty Worker IO Thread #0/WARN]: Event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@51e66f2e, receiver=HANAGE), cancelled=false, tag=lunachat:message) took 354ms to process!

**Comment by ucchyocean** [comment]
bungeePassThroughModeの時に、Spigot側でチャットを処理したときに、コンソールに
　<プレイヤー表示名> 発言内容
の様に表示したら解決します？

また、「PluginMessageEvent took 354ms to process!」は、処理に時間がかかっているという警告なので無視してください。
LunaChatは、GoogleIMEと通信してカナ漢字変換している都合上、処理にどうしても時間がかかります。

**Comment by lee3kfc** [comment]
機能的には、誰がどのタイミングで何を発言したかがspigotのログを見て把握出来れば問題無いと思います。よろしくおねがいします。

**Comment by ucchyocean** [comment]
了解です。
では、loggingNormalChatという設定を追加して、通常チャットの内容をログに記録するかどうかを選択できるようにしましょう。

bungeePassThroughMode構成なら、BungeeCord側はloggingNormalChat=falseに、各Spigotサーバー側はloggingNormalChat=trueにすれば、ご所望の動作になります。

**Comment by lee3kfc** [comment]
ありがとうございます。

**Comment by ucchyocean** [comment]
Fixed
v3.0.10で動作確認OK

設定名ですが、上記ではloggingNormalChatと記載しましたが、displayNormalChatOnConsoleに変更しました。ご了承ください。
