### ISSUE TITLE
Persists java.lang.StackOverflowError

### ISSUE THREAD

**Issue by KisaragiEffective** [ucchyocean/LunaChat#204]
**Describe the bug/バグの概要**

**Server and version/サーバーとバージョン**
- Server: Paper (build 1618)
- Server version (Minecraft version) : 1.12.2
- Other plugins: BKCommonLib, CoreProtect, DiscordSRV, dynmap, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP,
 EssentialsProtect, EssentialsSpawn, EssentialsXMPP, FastAsyncWorldEdit, FlySpeed, LuckPerms,  Train_Carts, Vault, WorldEdit, WorldGuard
ard
- LunaChat version : 3.0.12

**To Reproduce/再現手順**
1. Type `/ch create Global`
2. Then `/ch join Global`
3. Say something in there
4. And got 
```
[14:15:21 ERROR]: java.lang.StackOverflowError
```
for server (just one line), force kick for client (and got kicked everytime when something said).

**Expected behavior/期待する結果**
Didn't expect got kicked.

**Screenshots/スクリーンショット**
None

**Additional context/備考**
None

**Comment by ucchyocean** [comment]
![2020-09-05_23 29 52](https://user-images.githubusercontent.com/2563444/92307244-d3dd8400-efcf-11ea-860a-1ffc16f2ece6.png)

Paper-1618 + Minecraft 1.12.2 + LunaChat 3.0.12 
の組み合わせでテストしてみましたが、再現しませんね。
他のプラグインで、障害と何か関係のありそうなものは、心当たりありますか？

**Comment by ucchyocean** [comment]
ご回答をいただけていないので、このチケットは閉じさせてもらいます。
たぶんですが、#201 の問題と同じだと思いますので、LunaChatの最新版を試してみてください。既に解決している可能性があります。
