### ISSUE TITLE
Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Phoenix-Dev38** [ucchyocean/LunaChat#209]
**Describe the bug/バグの概要**
自作プラグインと併用して使うとエラーが表示されて、LunaChatのフォーマット通りにでない。

**Server and version/サーバーとバージョン**
- Server: Spigot
- Server version (Minecraft version) : 1.8.8
- Other plugins: Nick
- LunaChat version :  v3.0.13

**To Reproduce/再現手順**
自分ができないときもあれば、できるときもあります。
意図的に再現することは不可能かと思います。

**Expected behavior/期待する結果**
LunaChatのフォーマット通りにチャットが表示されるようにしたいです。

**Screenshots/スクリーンショット**
![2020-09-07_23 15 13](https://user-images.githubusercontent.com/12019840/92396532-1c2bac00-f160-11ea-8daa-c02d48f45f55.png)

**Additional context/備考**
下記のエラーがでます。
https://hastebin.com/sunefaxafo.pl

**Comment by ucchyocean** [comment]
発言したプレイヤーのPrefixが、nullになっているようです。
PrefixSuffixを設定すれば、問題を回避できると思います。
LunaChat側も、PrefixSuffixにnullが送られてきた場合にも対処できるように、nullを空文字列に変換する修正を検討します。

**Comment by xPhoenix38x** [comment]
> 発言したプレイヤーのPrefixが、nullになっているようです。
> 
> PrefixSuffixを設定すれば、問題を回避できると思います。
> 
> LunaChat側も、PrefixSuffixにnullが送られてきた場合にも対処できるように、nullを空文字列に変換する修正を検討します。
> 
> 

LunaChatはVaultでPrefix, Suffixを設定している感じでしょうか。

**Comment by ucchyocean** [comment]
Vault経由で、権限管理プラグイン（PermissionsExやLuckPermsなど）から、Prefix、Suffixを取得しています。

**Comment by xPhoenix38x** [comment]
> Vault経由で、権限管理プラグイン（PermissionsExやLuckPermsなど）から、Prefix、Suffixを取得しています。

ちなみにですがLunaChatのconfig.ymlのグローバルチャットのフォーマットの%displaynameはplayer#getDisplayNameなのでしょうか。

**Comment by ucchyocean** [comment]
Fixed
Prefix/Suffix取得箇所にnull保護を挿入した。
なお、再現できる環境が無いため、動作確認は通常動作のみ実施。
