### ISSUE TITLE
BungeeCord版でJapanizeをNetty IOスレッド外で動作させる

### ISSUE THREAD

**Issue by ken-kentan** [ucchyocean/LunaChat#210]
**Is your feature request related to a problem? Please describe.**

Google APIを介してJapanizeする際にNettyのIOスレッドをブロックし、BungeeCordのパフォーマンスを低下させる。
BungeeCordはNettyを使用しており、Netty IOスレッドでいかなるブロッキング処理も行うべきではありません。

特に、外部APIを叩くといった数百msのブロッキング処理を幾度もNetty IOスレッドで行うと著しいパフォーマンス低下を招きます。

**Describe the solution you'd like**

ブロッキング処理をNetty IOスレッド外で行う。
独自のスレッドプールを用意するか、BungeeCordの[TaskScueduler](https://ci.md-5.net/job/BungeeCord/ws/api/target/apidocs/net/md_5/bungee/api/scheduler/TaskScheduler.html)を使用してブロッキング処理を実行

**Describe alternatives you've considered**

`ChatEvent`をキャンセル後、Netty IOスレッド外でJapanize処理を実行

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
