### ISSUE TITLE
Expect updates

### ISSUE THREAD

**Issue by Stargazer-arc** [ucchyocean/LunaChat#212]
Not available in the latest version 1.16.3
Can be used without problems in 1.16.2

**Server and version/サーバーとバージョン**
- Server: Paper
- Server version:198
- Other plugins: 
- LunaChat version : v3.0.14

**Comment by ucchyocean** [comment]
LunaChat v3.0.14 has been tested on Minecraft1.16.3 already.
Do you have any problem with 1.16.3?

**Comment by ucchyocean** [comment]
ご回答をいただけていないので、このチケットは閉じさせてもらいます。
Stargeyser-arc did not answer in this issue, so I close it.
