### ISSUE TITLE
日本語変換をプレイヤにデフォルトで適用 *しない* 設定がほしい

### ISSUE THREAD

**Issue by ozelotjp** [ucchyocean/LunaChat#213]
**Is your feature request related to a problem? Please describe.**
私の運営しているサーバでは「ほとんど日本語を入力して発言する」「たまに英語（okayなど）を発言する」人が大多数であり、ごく一部の人しか日本語変換の機能を使用していません。
現在の仕様では `japanizeType: kana|GoogleIME` の場合で *japanize.yml* に値がないプレイヤの発言に日本語変換が適用されるため、毎回サーバに参加した人に `/jp off` を使用する必要があります。

**Describe the solution you'd like**
config.ymlに `japanizeDefault: true` のような項目を作成します。
*japanize.yml* に値がないプレイヤの発言に日本語変換が適用されるか選択できるようにします。

**Describe alternatives you've considered**
プレイヤがログインしたら自動で `/jp off` を実行させることも考えました。
しかし、このプラグインだけで設定できたほうが良いと思いました。

**Additional context**
例で出した `japanizeDefault: true` のキーは適当に考えた名前ですので、これである必要はありません。

**Comment by ucchyocean** [comment]
ozelotjpさん、LunaChatへのご要望をいただきありがとうございます。

`japanizeDefault` という設定名だと、チャンネルのJapanizeのデフォルトなのか、プレイヤーのJapanizeのデフォルトなのか、判断がつかないので、
`japanizePlayerDefault` にしますけれども、いいでしょうか。
`japanizePlayerDefault: false` なら、japanize.yml に名前がないプレイヤーは、`/jp off` になるようにします。
 `japanizePlayerDefault` のデフォルトは、`true`にさせていただきます。ozelotjpさんの用途の場合は、LunaChatをバージョンアップ後に `japanizePlayerDefault: false` を設定していただく必要があることを、ご了承ください。

**Comment by ucchyocean** [comment]
Fixed.
動作確認OK

**Comment by ozelotjp** [comment]
うっちぃさん、丁寧にお返事して頂きありがとうございます。

> `japanizePlayerDefault` にしますけれども、いいでしょうか。

はい、問題ありません。こちらの方が分かりやすいと思います。

> `japanizePlayerDefault` のデフォルトは、`true`にさせていただきます。

今までが`true`と同等の仕様のため、こちらもそのようにすべきだと私も思います。
`japanizePlayerDefault: false`を設定することで、望んでいた動作をするようになりました。

どうもありがとうございました！
