### ISSUE TITLE
個人チャットを自分自身に送れるようなオプション

### ISSUE THREAD

**Issue by Phoenix-Dev38** [ucchyocean/LunaChat#214]
**Is your feature request related to a problem? Please describe.**
BaseComponentのClickEventで/tellを使用し自分自身にメッセージを送信したいのですがLunaChat側で「自分自身にはプライベートメッセージは送信できません。」と出力されました。

**Describe the solution you'd like**
config.ymlにプライベートメッセージの設定の項目があると思うのでそこに allowSelfMsg 等の設定項目を追加してほしいです。

**Describe alternatives you've considered**
別の方法が思い浮かびませんでした。

**Additional context**
configの項目の名前はそれでなくても大丈夫です。

**Comment by ucchyocean** [comment]
すみませんが、機能追加の要望として不適切な内容だと判断したため、却下します。
- ユーザーのための機能追加ではなく、開発者のデバッグ用途の機能追加であるため。
- 複数プレイヤーが動作するサーバープラグインの開発者として、複数プレイヤーを扱えないような開発環境であること自体に問題があるため。（/tellコマンドだけが1人で実行できて開発できるようになったところで、その他の機能のテストもぜんぶ1人でできるわけではないから。）
