### ISSUE TITLE
チャットが日本語化されない

### ISSUE THREAD

**Issue by niwatori-chicken** [ucchyocean/LunaChat#220]
チャットが日本語化されないです。1週間前には動いていたのですが突如として使用不可能になりました
又エラーログなども全く出力されていない状態で再現等が難しいと思われます。

bungeecordでの使用です

configの再生製や/jp on <player name> 等試しましたがだめでした

その時の映像を載せておきます

https://user-images.githubusercontent.com/83861617/117533069-a4cb5680-b025-11eb-8e7b-55cf0270a89c.mp4

**Comment by Taitaitatata** [comment]
config.ymlの`japanizeType`を`GoogleIME`にしたら治ると思います。
```yml
# 略
# -------------------- Japanize conversion settings --------------------

# Settings for converting Roman characters to Kana or Kanji.
# You can set any one of none/kana/GoogleIME.
# none: No conversion.
# kana: Kana conversion only.
# GoogleIME: After converting kana, convert kanji using GoogleIME.
japanizeType: GoogleIME

# 略
```
