### ISSUE TITLE
[Peper1.17.1]サーバー起動時に警告が出る

### ISSUE THREAD

**Issue by mayu0326** [ucchyocean/LunaChat#223]
**Describe the bug/バグの概要**
プラグイン自体は正常に動いているのですが、
サーバーに起動時に毎度「Legacy plugin」についての警告が出るので、
お手すきの際に確認、更新していただきたいです。

**Server and version/サーバーとバージョン**
- Server:  Paper 
- Server version (Minecraft version) : 1.17.1 
- Other plugins: 
- LunaChat version : LunaChat v3.0.16

**To Reproduce/再現手順**
1. プラグインを導入してサーバーを起動する
2. サーバーの起動ログを確認する
3. 警告が表示される
4. サーバー自体は正常に起動しプラグインも使える

**Expected behavior/期待する結果**
A clear and concise description of what you expected to happen./上記の再現手順に書いた状態について、
何か期待と違っていたのか、どこに問題があったのかを、明確に記載してください。

Legacy plugin LunaChat v3.0.16 does not specify an api-version.というログが出ているので、
この表示がされないようにしてほしい。

**Screenshots/スクリーンショット**
If applicable, add screenshots to help explain your problem./スクリーンショットがあれば添付してください。
ブラウザに画像ファイルをドラッグアンドドロップしてアップロードできます。

[12:31:59] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[12:32:02] [Server thread/WARN]: Legacy plugin LunaChat v3.0.16 does not specify an api-version.

**Additional context/備考**

スクリーンショットじゃなくてすみません。
よろしくお願いします。

**Comment by ghost** [comment]
Dear Operation, Don't Think This Is Spam <3
運営ではないし、今更なのですが書きます; ;
エラーを見てみてると分かりますが、これはバグではなくて対応しているバージョンの問題だと思います。
この場合1.17.1 = 対応してないバージョンで動かしているのでバグではありません。

**Comment by Laica-Lunasys** [comment]
@mayu0326 @e4-line 
報告、並びに補足頂きましてありがとうございます。

こちらはplugin.ymlにapi-versionが定義されていないため表示されている警告になります。
そのため、警告は表示されるものの (基本的には)プラグインを引き続き使うことができます。

使用時に問題が発生されるようでしたら別途Issueにてお知らせいただけますと幸いです。

**Comment by ghost** [comment]
@Laica-Lunasys 
なるほどですね。plugin.yml見てませんでした....
@mayu0326 
しっかり確認してなかったです。すいません **sigh** 
Legacy plugin LunaChat v3.0.16 does not specify an api-version. はそもそも指定してませんって言ってましたね; ;
前違うバージョンの自作プラグイン入れたときこうなったしSpigotフォーラムでもそう言われてて誤解してました

あと自分で悪用される可能性があるIssueを出しているので確認・修正をお願いします。
