### ISSUE TITLE
Bukkit#getOfflinePlayer()のレート制限によるクラッシュ

### ISSUE THREAD

**Issue by ghost** [ucchyocean/LunaChat#228]
**Describe the bug/バグの概要**

**Server and version/サーバーとバージョン**
- Server: git-Paper-411
- Server version (Minecraft version) : 1.17.1
- Other plugins: Lens(自作のものです)
- LunaChat version : v3.0.16

**To Reproduce/再現手順**
1. msg a aaaaaをスパムします
以下を参照してください
https://textbin.net/no4bqrjp92

**Expected behavior/期待する結果**
このエラーが出力されるのを修正すること

**Additional context/備考**
多分Bukkit#getOfflinePlayer()でmojang api(?)にリクエストした時にレート制限になってメインスレッドが停止にラグが発生するのだと思われます。
意外と知られている手法(?)らしいので出来るだけ早めの修正をお勧めします。

タイトルの日本語おかしいですが許してください :p

**Comment by AerialLine** [comment]
ps: おそらくmsgだけではないと思います
